

py_test(
    name = "attention_layer_eager_test",
    srcs = ["attention_layer_eager_test.py"],
    deps = [

    ],
)

py_test(
    name = "cnn_cell_eager_test",
    srcs = ["cnn_cell_eager_test.py"],
    deps = [

    ],
)

py_test(
    name = "decoder_eager_test",
    srcs = ["decoder_eager_test.py"],
    deps = [

    ],
)

py_test(
    name = "conv1d_glu_graph_test",
    srcs = ["conv1d_glu_graph_test.py"],
    deps = [

    ],
)

py_test(
    name = "conv1d_graph_test",
    srcs = ["conv1d_graph_test.py"],
    deps = [

    ],
)

py_test(
    name = "conv1d_incremental_graph_test",
    srcs = ["conv1d_incremental_graph_test.py"],
    deps = [

    ],
)

py_test(
    name = "frontend_graph_test",
    srcs = ["frontend_graph_test.py"],
    deps = [

    ],
)

py_test(
    name = "linear_graph_test",
    srcs = ["linear_graph_test.py"],
    deps = [

    ],
)

py_test(
    name = "model_graph_test",
    srcs = ["model_graph_test.py"],
    deps = [

    ],
)

py_test(
    name = "positional_encoding_graph_test",
    srcs = ["positional_encoding_graph_test.py"],
    deps = [

    ],
)

py_test(
    name = "weight_normalization_graph_test",
    srcs = ["weight_normalization_graph_test.py"],
    deps = [

    ],
)